[package]
name = "ucfirst"
version = "0.2.1"
edition = "2021"
description = "Uppercase the first letter of a string"
repository = "https://github.com/qtfkwk/ucfirst"
license = "MIT"
keywords = [ "casing", "case", "string", "capital", "uppercase" ]
categories = [ "text-processing" ]
